<!doctype html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no" />
<title>外汇投资交易财经日历 - 金道环球投资</title>
<link rel="stylesheet" href="http://www.gwfx.com/public/css/global.css" />
<link rel="stylesheet" href="http://www.gwfx.com/public/css/data_ver3.0.css" />
<link rel="stylesheet" href="http://www.gwfx.com/public/floatBox/css/base.css" />

<link href="/gwfx/css/zixun.css" type="text/css" rel="stylesheet" />
<script src="http://www.gwfx.com/public/js/jquery.min.js" type="text/javascript"></script>
<script type="text/javascript" src="http://www.gwfx.com/public/js/finance.js" type="text/javascript"></script>
<script type="text/javascript" src="http://www.gwfx.com/public/js/My97DatePicker/WdatePicker.js"></script>
<script type="text/javascript">
 var oaPath='http://oa.gwfx.com';
 var lang='zh';
function searchDateFun(){
	var d=$("#searchDate").val();
	
	if(typeof(d)=='undefined' || $.trim(d)==''){
		alert("请选择查询日期");
		return;
	}
	location.href='/calendar/gwfxtw/'+d+".html";
}
</script>
</head>

<body>
    <div class="rili-box">
	<?php echo $datas;?>  
</div>
</body>
</html>